name: mlp
channels:
  - defaults
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - python=3.11
  - jupyter
  - nbconvert
  - numpy
  - matplotlib
  - pytorch::pytorch
  - pytorch::torchvision
  - nvidia::cudatoolkit